//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int id { get; set; }
        public int Status { get; set; }
        public string No { get; set; }
        public int CompanyId { get; set; }
        public int CityId { get; set; }
        public int AirportId { get; set; }
        public bool Type { get; set; }
        public int GateId { get; set; }
        public int RunwayId { get; set; }
        public System.DateTime FlightDate { get; set; }
        public Nullable<int> Late { get; set; }
    
        public virtual Airports Airports { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual Gates Gates { get; set; }
        public virtual Runways Runways { get; set; }
    }
}
